networks:
  ui-development:
    name: ui-development
    driver: bridge

services:

  frontend-dev:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
      args:
        # Docker image versions
        NODE_VERSION: "22.4"        # https://hub.docker.com/_/node/tags
    container_name: frontend-dev
    hostname: frontend-dev
    networks:
      - ui-development
    ports:
      - "3000:3000"
    restart: "no"
