networks:
  ui-development:
    name: ui-development
    driver: bridge

services:

  frontend-dev:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
      args:
        # Docker image versions
        NODE_VERSION: "22.4"        # https://hub.docker.com/_/node/tags
        # Environment variables (set in project .env file)
        REST_ENDPOINT_URL: "https://internal.axihub.ca/folding" # "http://127.0.0.1:8079/folding" Use this one eventually
    container_name: frontend-dev
    hostname: frontend-dev
    networks:
      - ui-development
    ports:
      - "3000:3000"
    restart: "no"
