name: Javascript CI

on:
  push:
    branches: [ master ]

jobs:
  analyze:
    name: Javascript Analysis
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7

      # Additional JavaScript Analysis
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3.25.11
        with:
          languages: 'javascript'

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3.25.11

        # SonarQube Analysis
      - name: Execute SonarQube Scan
        env:
          SONAR_HOST: ${{ vars.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONARQUBE_PAT }}
        run: |
          docker run \
          --rm \
          -e SONAR_HOST_URL=${{ vars.SONAR_HOST_URL }} \
          -v "$(pwd):/usr/src/" \
          sonarsource/sonar-scanner-cli:10.0 \
            -Dsonar.projectKey=folding-stats-ui  \
            -Dsonar.projectName=folding-stats-ui  \
            -Dsonar.sources=/usr/src/src/ \
            -Dsonar.token=${{ secrets.SONARQUBE_PAT }}
